// Learn — the lesson library, milestones and the broker's Teaching Studio.
// LESSONS/MILESTONES are content, not logic, and are the bulk of the weight here.
// Extracted from App.js (strangle the monolith, step 25).
import React, { useCallback, useEffect, useState } from 'react';
import { supabase } from '../dataService';
import { lbl, money } from '../helpers';
import { tipsSeenList } from '../tipsUi';

export const LESSONS = [
  // ── Using Prism — the feature guide (the manual). How to actually use each
  //    part of PrismOS. Same card format as the coaching lessons, so they slot
  //    into Learn with progress + a milestone for free.
  { id:'up_today', cat:'Using Prism', title:'Start your day in Today', body:'Today is your home screen — it answers "what do I need to do next?" by scanning every signal at once: who owes you a reply, what\'s due, today\'s appointments, leads going cold. Open it first thing and work the list top to bottom. You never have to wonder where to start.', deeper:'Today replaces the old dashboard. When nothing is urgent it doesn\'t leave you at a dead end — it pivots to the highest-value growth move (a follow-up, a person to reconnect with). Tap any item to act on it right there. Think of Today as Prism\'s answer to "if I only had 30 minutes, what should I do?"' },
  { id:'up_nba', cat:'Using Prism', title:'Trust "Do This Next"', body:'The "Do This Next" card surfaces the single highest-leverage action across your whole business — not just the loudest one. It weighs replies owed, cadence due, appointments, and deals, then picks one. When you\'re not sure what to do, do what it says.', deeper:'This is the engine behind Today. It exists to kill decision fatigue — the hundred tiny "what now?" moments that burn a day. Give it a week of honest use and notice how much less you drift. If a suggestion isn\'t right, skip it and it moves on; over time it learns your rhythm.' },
  { id:'up_research', cat:'Using Prism', title:'Research anyone before you talk to them', body:'Open a contact and tap Research. Prism searches the public web, confirms it\'s the right person, and builds a sourced profile — their background, what they care about, and a behavioral read — so you walk into every conversation already knowing who you\'re talking to.', deeper:'The single best thing you can do to make research sharp: add an email, phone, or a LinkedIn/Instagram in the contact\'s Details tab first. A profile URL pins the right person instantly. Research takes about a minute — the fork animates while it works through searching, cross-referencing, and building the read. The result saves to the contact, so you only run it once.' },
  { id:'up_disc', cat:'Using Prism', title:'Read the DISC on every contact', body:'Each contact carries a DISC read — D (direct), I (social), S (steady), C (analytical) — shown as four colored bars. It tells you how they decide so you can flex your approach: bottom-line for a D, warm for an I, patient for an S, detailed for a C. Glance at it before any call.', deeper:'The read gets sharper the more Prism knows — from research, from recorded calls, from your notes. An "early read" is a hypothesis to test on the next call, not gospel; a confirmed read is backed by real evidence. The color bars are the fast version; open the card for the "how to work with them" guidance.' },
  { id:'up_socials', cat:'Using Prism', title:'Add socials to sharpen everything', body:'In a contact\'s Details tab, add their LinkedIn, Instagram, Facebook, or website. It\'s not just for reference — Prism feeds those profiles into research as anchors, so it locks onto the right person and reads them far more accurately. Better in, better out.', deeper:'A LinkedIn URL is the strongest identifier there is — stronger than a name or email, because names collide and profiles don\'t. Type a full URL, an @handle, or just a username; Prism figures out the link. This works for every person-type — leads and recruits too, not just contacts.' },
  { id:'up_myvoice', cat:'Using Prism', title:'Teach Prism your voice', body:'Set up MyVoice once and every draft Prism writes for you sounds like you — your phrasing, your warmth, your level of formality — while still adapting to how the recipient likes to be talked to. Your words, their style, every send.', deeper:'MyVoice applies to outbound client drafts, never to your private briefing (Prism talks to you plainly; it only puts on your voice when talking to others for you). Give it a few real samples of how you write and it learns the pattern. The magic is the combination: it sounds like you AND lands right with a D or an S — two things most agents can only do one of.' },
  { id:'up_ari', cat:'Using Prism', title:'Ask Ari to do the work', body:'Ari is your AI assistant — ask it in plain language to draft a message, prep you for a call, pull up what you know about someone, or plan your day. It has permission-gated access to your data, so it can actually act, not just chat.', deeper:'Ari is most useful when you talk to it like a capable assistant, not a search box: "draft a warm check-in to the Hendersons about their inspection" beats "Henderson." It respects the same DISC and voice intelligence as the rest of Prism, so what it drafts is already tuned to the person. When it needs permission to do something sensitive, it asks first.' },
  { id:'up_library', cat:'Using Prism', title:'Put everything in the Library', body:'The Library is one searchable home for every note, journal entry, call transcript, and document. Capture with the + menu — a quick note, a photo, a voice memo, a file. Everything is full-text searchable, so nothing you capture is ever lost.', deeper:'It replaces the pile of apps most agents juggle. Notes are living documents you edit; journal entries and call transcripts are records, shown read-only so history stays honest. Anything you capture can be linked to a person, property, or deal, and it surfaces when you\'re looking at that thing. Capture in the moment; trust the search later.' },
  { id:'up_record', cat:'Using Prism', title:'Record calls and meetings', body:'Record your conversations and Prism transcribes them, extracts the to-dos, and feeds the behavioral read — turning talk that would fade by dinner into permanent, searchable intelligence. Review each recording to confirm who you met with, and it does the rest.', deeper:'On a connected voice recorder, recordings back up to the cloud and flow in automatically; on iPhone, the share-sheet shortcut sends them in. Florida is a two-party-consent state, so announce that you\'re recording. The payoff compounds: every captured conversation makes Prism\'s read on that person sharper and your memory of promises perfect.' },
  { id:'up_review', cat:'Using Prism', title:'Clear Review daily', body:'Review is Prism\'s inbox to you — a recording to label, a task it heard on a call, a suggestion to confirm. Spend two minutes clearing it: confirm what\'s real (it graduates into Tasks with a priority) and dismiss the rest. Your task list stays trustworthy.', deeper:'Two modes, two places: Review is for deciding, Tasks is for doing. Keeping them separate is why your task list never rots into a pile of things you never actually committed to. Clear it once a day — end of day is ideal — and both Review and Tasks stay clean.' },
  { id:'up_tasks', cat:'Using Prism', title:'Let Prism schedule your tasks', body:'Add a task with a priority and, if you want, a duration and deadline. Prism\'s auto-scheduler fits it into your open calendar time around your appointments, so your to-dos have a real home instead of floating. Your day plans itself around what matters.', deeper:'Priorities sort by urgency and importance (A/B/C/D). The scheduler protects your important-but-not-urgent work — prospecting, follow-up — before the day fills with noise. If something can\'t fit, Prism tells you honestly rather than silently dropping it. You stay in control; it just does the tetris.' },
  { id:'up_someday', cat:'Using Prism', title:'Park it in Someday, not the trash', body:'Not every idea is a now-task. Move it to Someday/Maybe and it leaves your active list without being lost — a real backlog you can revisit. The stale-task groomer will even propose moving old items there, but it never archives anything silently.', deeper:'The discipline that keeps a task list trustworthy: everything on it is something you actually intend to do soon. Someday is the pressure valve — it lets you say "not now" without saying "never." Review your Someday list occasionally and pull things back when their time comes.' },
  { id:'up_comms', cat:'Using Prism', title:'Never lose track of who owes whom', body:'Prism tracks the direction of every conversation — who wrote last and whether you owe a reply. The contact card shows it plainly: "↓ They" means the ball\'s in your court, "✓ Settled" means you\'re square. When someone writes back after you settled, it re-arms automatically.', deeper:'This runs across your email and texts so nobody falls through the cracks. Mark a thread "settled" or "no reply needed" when you\'re done and it drops off your radar — but if that person reaches out again, it comes right back. The whole point is that "who am I forgetting to answer?" stops being a thing you carry in your head.' },
  { id:'up_inbox', cat:'Using Prism', title:'Work both inboxes with AI triage', body:'Prism connects both your Gmail accounts and reads them for you — summarizing threads, flagging what needs a reply, and drafting responses in your voice. You spend your inbox time deciding and sending, not reading and scrolling.', deeper:'It surfaces the emails that actually need you and lets the rest wait. Drafts come pre-written in your voice and tuned to the recipient — edit and send. You can file an email\'s attachments straight into the Library, or turn an email into a task, without leaving the thread. The inbox stops being a place you lose an hour and becomes a place you spend ten focused minutes.' },
  { id:'up_quo', cat:'Using Prism', title:'Call and text from Quo', body:'Quo is your calls-and-texts hub — a live feed of every call and message through your business line, with recordings and transcripts flowing straight into each contact. Reach out, follow up, and see the whole history in one place.', deeper:'Because it\'s tied to your contacts, every call and text becomes part of that person\'s record — no separate log to keep. Calls can auto-record and transcribe (announce it — two-party consent), feeding the same intelligence as your meetings. Text and call from the same place you manage the relationship.' },
  { id:'up_cadence', cat:'Using Prism', title:'Set a cadence and let Prism keep it', body:'Give a contact a cadence — every 30, 60, 90 days — and Prism reminds you when it\'s time to reach out. You stay top-of-mind on a rhythm instead of only calling when you need something, which is exactly how referrals get earned.', deeper:'Set it once per person (or per tier — your A\'s more often than your C\'s) and Prism does the remembering. When a touch is due, it shows up in Today. The reminder isn\'t "you\'re behind" — it\'s "here\'s a warm, easy chance to stay in someone\'s life." Consistency you don\'t have to hold in your head is the whole game.' },
  { id:'up_calendar', cat:'Using Prism', title:'One calendar, always in sync', body:'Prism\'s calendar syncs both ways with Google, so what you schedule here shows up on your phone and vice versa. Appointments, tasks Prism scheduled, and your synced events all live in one view — the real picture of your time.', deeper:'After Prism creates an event, open the Calendar tab so the sync runs and it lands on Google. Contact-linked, timed appointments feed your production numbers automatically. The calendar is where auto-scheduled tasks land too, so protecting a prospecting block here actually protects it everywhere.' },
  { id:'up_deals', cat:'Using Prism', title:'Track deals and your GCI', body:'The Deals room is your pipeline and your commission tracker in one — every active deal, its stage, and what it\'s worth to you. Watch your GCI build toward your goal and see exactly which deals are carrying the year.', deeper:'Working backward from your GCI goal is how prospecting becomes math instead of vague pressure. Deals also drive Prism\'s AI listing and post-close workflows — the orchestrators that prep a new-lead plan, a listing presentation, or a post-close nurture. Keep the pipeline current and the whole business becomes something you can steer by the numbers.' },
  { id:'up_recruiting', cat:'Using Prism', title:'Grow and manage your roster', body:'The Recruiting room holds your agent roster, their earnings, and your brokerage lead engine. Tag any contact as "Our Agent" and they join the roster automatically — no double entry — so your team list is always complete.', deeper:'The roster powers everything team-related: leaderboards, commission plans, delegation. Because tagging a contact as an agent now auto-adds them, the old problem of "why isn\'t this person showing up?" is gone. Use it to see your team\'s production at a glance and to route brokerage leads to the right agent.' },
  { id:'up_journal', cat:'Using Prism', title:'Capture thoughts in the Journal', body:'The Journal is for the thought you have in the moment — a client detail, a follow-up, a reflection. Jot it and Prism files it against the right person and can summarize your days and weeks. Your mind is for having ideas, not holding them.', deeper:'Every open loop in your head is a tax on your attention; writing it down frees you to be present. Prism analyzes entries, links them to people, and can hand you a period summary when you want the big picture. Journal entries live in the Library too, searchable forever — capture once, find it whenever.' },
  { id:'up_brain', cat:'Using Prism', title:'Search your whole memory in Brain', body:'Brain is semantic search across everything Prism knows — ask in plain language ("what did I promise the Reyes family?") and it finds the answer across your notes, calls, and history, even if you don\'t remember the exact words. It\'s your second brain.', deeper:'Unlike a keyword search, semantic search understands meaning — it finds the right memory even when your query and the original note use different words. The more you capture, the more powerful Brain becomes. This is what turns "I think we discussed…" into "here\'s exactly what was said."' },
  { id:'up_docx', cat:'Using Prism', title:'Export a research report as a Word doc', body:'From any contact\'s research report, tap "Word report" and pick who it\'s for. The client dossier is a polished, shareable bio — no behavioral read, no coaching. The agent prep sheet adds the DISC read but still hides the rapport and things-to-avoid notes. Both come branded as Realty ONE Group Advantage.', deeper:'This is how research becomes something you can hand to a client, a co-agent, or a referral partner — a professional one-pager instead of a raw dump. The two modes matter: never share the coaching (how to work someone) with the person themselves. The doc is built on the fly, so it always reflects the latest research on file.' },
  { id:'up_multiparty', cat:'Using Prism', title:'Calls and meetings with 3+ people', body:'When a call or meeting has more than two people, Prism now identifies each extra person and attributes their commitments to them by name — not just "you" or "them." If someone else promised something, it lands as a follow-up on the right person. Review shows who owes what; tap the owner chip to correct it if the guess is off.', deeper:'Prism guesses who the third voice is from the conversation and matches them to your contacts. When the person on the hook is one of your agents, the task can route straight to their list — real delegation, not just a note to chase them. The correction is one tap: "You / the caller / + Someone else." Fix the owner once and the task follows the right person.' },
  { id:'up_simplify', cat:'Using Prism', title:'Simplify PrismOS to just what you use', body:'Settings has a "Simplify PrismOS" panel that lists every page with an on/off switch, grouped by area. Turn off what you don\'t use and it disappears from every menu — the sidebar and the tab bar both. Your data stays put; flip a page back on any time. A couple of essentials (Today, Settings) can\'t be turned off so you never lock yourself out.', deeper:'This is how you make PrismOS feel light instead of overwhelming — an agent who only does listings can hide the recruiting and finance pages and never see them again. Hiding is per-person, so what you turn off doesn\'t affect anyone else. It\'s cosmetic, not a lock: a hidden page still works if Ari or a link sends you there.' },
  { id:'up_push', cat:'Using Prism', title:'Turn on push notifications', body:'Let Prism tap you on the shoulder — your morning briefing, a reply you owe, a task coming due. Go to Settings, find Notifications, tap Enable notifications, and allow when your phone asks. Then tap Send test notification to confirm it landed. On Android that\'s all it takes.', deeper:'On iPhone there\'s one extra step, and it\'s required by Apple: first add PrismOS to your Home Screen (in Safari, tap the Share button, then Add to Home Screen), then open Prism from that new home-screen icon — not from the Safari tab. Now go to Settings, Notifications, Enable, allow, and send yourself a test. iPhone only delivers app notifications to an installed app, which is why the Home Screen step matters. Do this once per device; if you use Prism on both a phone and a tablet, enable it on each.' },
  { id:'up_unlock', cat:'Using Prism', title:'Unlocking extra features', body:'Some PrismOS features are part of add-on packages. If your broker gives you an unlock code, go to Settings → Unlock features, enter it, and the pages turn on immediately. If you land on a locked page, the same code box is right there. Your base features are always yours — codes only add to what you already have.', deeper:'Brokers and owners generate these codes and can grant features to an agent directly. One code can unlock several features at once, and what you unlock is tied to your account, so it follows you. If a page you expected is missing, it\'s likely part of a package your plan doesn\'t include yet — ask your broker.' },
  { id:'up_learn', cat:'Using Prism', title:'Keep leveling up in the Field Guide', body:'This is the Prism Field Guide — short lessons on both the craft of real estate and how to get the most from Prism. Work through them at your own pace or let them surface as tips while you work. Track your progress and earn milestones as you go.', deeper:'The lessons are the "why" behind the workflow — read one when you have a spare minute and it compounds. Tips also appear in context on the screens they relate to, one per visit, so you learn the app by using it. Set how often they surface in Settings → Learning pace.' },

  { id:'nba', cat:'Your day', title:'Do this next', body:'Top producers don\'t do more — they do the right thing next. Prism scans every signal (tasks, who owes you a reply, cadence, appointments, deals) and surfaces the single highest-leverage move, so you never open the app wondering where to start.', deeper:'The hardest part of this business isn\'t effort, it\'s decision fatigue — a hundred small "what should I do now?" moments that quietly burn your day. The one-tap next action removes that friction: when nothing is urgent, it pivots to the highest-value growth move instead of leaving you at a dead end. Trust it for a week and notice how much less you drift.' },
  { id:'review', cat:'Your day', title:'Decide here, do in Tasks', body:'Review is Prism\'s inbox to you — a recording to label, a to-do it heard on a call. Confirm what\'s real and it graduates into Tasks with a priority; dismiss the rest. Your task list stays only what you chose to do, so it never gets noisy.', deeper:'Two mental modes, two places: Review is for deciding, Tasks is for doing. Mixing them is why most task lists rot — half the items were never really commitments. Clear Review daily (it takes two minutes) and your task list becomes something you actually trust, which is the whole point of having one.' },
  { id:'plan_ahead', cat:'Your day', title:'Plan tomorrow tonight', body:'Spend two minutes at the end of the day setting up the next one — confirm your top three, protect your prospecting block, clear Review. You start tomorrow already in motion instead of deciding what to do while the day slips.', deeper:'Willpower is highest in the morning — don\'t spend it deciding, spend it executing. A plan made the night before turns the first hour from "what now?" into "go." Prism\'s Plan My Day and briefing are built for exactly this handoff between today-you and tomorrow-you.' },
  { id:'eisenhower', cat:'Your day', title:'Urgent vs. important', body:'A/B/C/D sorts work by urgency and importance. The trap is living in "urgent." The important-but-not-urgent work — prospecting, follow-up, your database — is where your future income is built, so protect it before the day fills up.', deeper:'Urgent things announce themselves; important things wait quietly. That\'s why prospecting always loses to a ringing phone unless you defend it. The discipline is simple but rare: do one important-not-urgent thing before you touch the urgent pile, every day.' },
  { id:'blocking', cat:'Your day', title:'Protect the money hours', body:'Block your prospecting and follow-up time on the calendar like a listing appointment you can\'t move. The agents who hit their number treat lead-gen as a standing appointment with their business, not something they get to only if there\'s time left over.', deeper:'If it\'s not on the calendar, it\'s a wish, not a plan. Put your money hours in the same slot every day so it becomes a reflex, not a decision. Guard that block ruthlessly — the deals two months out are being made or missed right there.' },
  { id:'disc', cat:'Your people', title:'Reading the room (DISC)', body:'People decide in four styles — D (fast, results), I (social, enthusiastic), S (steady, relationship-first), C (analytical, detail). Match how you communicate to how they\'re wired and everything gets easier. Prism reads each contact\'s style and tunes your messages to it.', deeper:'You naturally sell the way YOU like to buy — that\'s why you click with some clients and grind with others. The skill is flexing: bottom-line and fast for a D, warm and social for an I, patient and reassuring for an S, thorough and proof-driven for a C. Prism does the first read for you; your job is to notice it and adjust your tone.' },
  { id:'cadence', cat:'Your people', title:'Consistency compounds', body:'Set a cadence and Prism reminds you when it\'s time to reach out — so you stay top-of-mind on a rhythm instead of calling only when you need something. Small, steady touches are how sphere-based agents earn referrals on repeat.', deeper:'Referrals go to whoever is top-of-mind at the moment someone says "we\'re thinking of moving" — not to the best agent, the remembered one. A light, genuine touch every 60–90 days beats a heavy push once a year. Set the rhythm once and let Prism keep the beat.' },
  { id:'database', cat:'Your people', title:'Everyone goes in', body:'The single highest-ROI habit in real estate: add every person you meet to your database, then work it. Your next ten deals are already hiding in the people you already know — you just have to stay in front of them.', deeper:'Agents chase cold leads while a goldmine of warm relationships goes cold from neglect. A name in your phone isn\'t a database — a name with a cadence and notes is. Share a contact into PrismOS or add them on the spot, and they\'re in the system that keeps them warm.' },
  { id:'speed', cat:'Your people', title:'Speed wins', body:'The first agent to respond usually wins the deal — a lead\'s value drops by the minute. Prism surfaces who\'s waiting on you and helps you reply fast and well, so speed never costs you quality.', deeper:'Studies put it starkly: responding in five minutes versus thirty can multiply your odds of connecting many times over. Most agents lose deals not to a better pitch but to a faster one. Let Prism flag who\'s owed a reply so nobody waits long enough to call someone else.' },
  { id:'gci', cat:'Your business', title:'Know your number', body:'Work backward from the income you want: GCI to deals to appointments to conversations. Once you know how many conversations a week hit your goal, prospecting stops being vague pressure and becomes a countable habit.', deeper:'"Make more money" is not a plan; "have 20 conversations a week" is. When you know your conversion — conversations to appointments to deals — the whole year becomes arithmetic you can actually run. Track the leading number (conversations), because it\'s the only one you fully control.' },
  { id:'systems', cat:'Your business', title:'One system, 90 days', body:'Pick one lead-gen system and run it for 90 days before you judge it. Most agents quit a system right before it works, chasing the next shiny object. Consistency in one channel beats dabbling in five.', deeper:'Every lead source has a lag between effort and payoff — quit early and you eat all the cost with none of the return. Ninety days of honest, daily reps is enough to know if a channel is yours. Master one before you add a second; five half-run systems produce less than one run well.' },
  { id:'followup', cat:'Your business', title:'The fortune is in the follow-up', body:'Most sales happen after the fifth contact — and most agents quit after the second. The lead who "went quiet" usually just wasn\'t ready yet. A patient, systematic follow-up is the cheapest deal flow you\'ll ever build.', deeper:'"Not now" is not "no" — it\'s "later," and later is where the money is. The agent who\'s still gently there in month six wins the deal the agent who gave up in week two walked away from. Put every promising lead on a follow-up cadence so persistence runs on autopilot instead of willpower.' },
  { id:'record', cat:'Your memory', title:'Record everything', body:'The more real conversations Prism hears, the sharper its read on each person — their DISC, what they care about, what you promised. Recording your meetings and calls turns every conversation into lasting intelligence instead of a memory that fades by dinner.', deeper:'You forget 80% of a conversation within a day — including the small personal details that build real relationships. Recorded and transcribed, every meeting becomes searchable memory: what they said, what you committed to, who else was in the room. That\'s the difference between "I think we talked about..." and knowing.' },
  { id:'capture', cat:'Your memory', title:'Capture beats recall', body:'Your mind is for having ideas, not holding them. Jot it in the Journal the moment it happens — a client detail, a follow-up, a thought — and Prism files it against the right person and pulls it back when it matters.', deeper:'Every open loop you\'re holding in your head is a tax on your attention. Write it down and your mind is free to be present with the person in front of you. Capture in the moment, trust the system to resurface it — that\'s how the calmest top producers run so much without dropping things.' },
  { id:'prep', cat:'Your memory', title:'Let Prism prep you', body:'Before a call or showing, Prism can surface what it already knows — their DISC style, your last conversation, what you promised, the research it pulled. Walk in prepared without spending an hour digging.', deeper:'Preparation is the cheapest edge in this business, and the one most agents skip because it\'s tedious. When the notes, history, and behavioral read are one tap away, "winging it" stops being your only option on a busy day. Two minutes of prep is what makes a client feel like they\'re your only client.' },
  { id:'cloud_recordings', cat:'Your memory', title:'How recordings flow in', body:'Record a meeting on your voice recorder — it backs up to Dropbox, and PrismOS watches the folder you pick. New recordings appear in Review to label who you met with; then Prism transcribes them and researches each person for you, hands-free.', deeper:'The magic is that it\'s automatic: once the folder is connected, you just record and forget. On iPhone, the Save to PrismOS shortcut does the same from any share sheet. The less friction between "we talked" and "it\'s in the system," the more of your real work actually gets captured.' },
  { id:'energy', cat:'Your day', title:'Match the task to your energy', body:'Your focus isn\'t flat across the day — you have peak hours and valley hours. Spend your peak on the work that moves money (prospecting, negotiations, hard conversations) and save email and admin for the valleys. Most agents do it backward and wonder why the important work never gets their best.', deeper:'Guard your first 90 minutes especially — before the day\'s noise starts pulling at you, your willpower and focus are highest. One hour of peak-energy prospecting beats three hours of tired dialing. Watch your own rhythm for a week, then build your calendar around it instead of against it.' },
  { id:'batching', cat:'Your day', title:'Batch it, don\'t scatter it', body:'Every time you switch between calls, emails, and errands, your brain pays a hidden tax to re-focus. Group like with like — a block of calls, a block of emails, a run of showings — and you\'ll do more in less time with less fatigue. Scattered effort feels busy but produces little.', deeper:'Context-switching can quietly cost you a quarter of your productive time — and because it\'s invisible, it\'s easy to ignore. Silence notifications during a batch so the block stays clean. The goal isn\'t to do many things at once; it\'s to do one kind of thing well, then the next.' },
  { id:'two_minute', cat:'Your day', title:'If it takes two minutes, do it now', body:'When something crossing your desk would take under two minutes — a quick reply, a small confirmation — just do it. Tracking it, scheduling it, and coming back to it costs more than the task itself. Save your task list for the work that actually deserves a slot.', deeper:'The two-minute rule keeps small things from piling into a mountain of low-grade guilt. It\'s not license to let them interrupt deep work — clear them in a gap or at the end of a batch — but when you\'re already in your inbox, knock them out on contact. A hundred two-minute things left undone is what makes a list feel unbeatable.' },
  { id:'close_loops', cat:'Your day', title:'End the day at zero', body:'Take five minutes before you log off to close the day\'s loose ends — clear Review, send the replies you owe, jot tomorrow\'s top three. You sleep better, and you start tomorrow clean instead of digging out of yesterday.', deeper:'Unfinished loops don\'t stay at the office — they follow you home as background stress. Closing them is less about the tasks and more about the signal to your brain that the day is genuinely done. A clean end is what makes a strong start possible.' },
  { id:'say_no', cat:'Your day', title:'Protect the yes', body:'Every yes to busywork is a quiet no to the work that pays you. Open houses for the wrong listings, coffees that go nowhere, tasks someone else could do — they feel productive but crowd out prospecting and follow-up. Guard your time like the finite inventory it is.', deeper:'You can\'t out-hustle a calendar full of the wrong things. The hardest discipline in this business is saying no to good opportunities so you can say yes to the great ones. Before you agree to anything, ask: is this dollar-productive, or does it just feel like work?' },
  { id:'listen', cat:'Your people', title:'Talk less, sell more', body:'The best agents ask questions and then get quiet. People tell you exactly how to help them if you stop pitching long enough to hear it. A client who feels heard trusts you; a client who feels sold runs.', deeper:'Aim to listen about twice as long as you talk. The pause right after they answer is where the real information lives — resist filling it. Record the conversation (with a heads-up) so you can be fully present instead of scrambling to take notes; Prism remembers the details for you.' },
  { id:'motivation', cat:'Your people', title:'Find the why behind the move', body:'Nobody buys or sells a house for the house — they\'re chasing a new job, more space, fewer stairs, a fresh start, or a way out of something. Find the real motivation and you stop selling and start solving. That\'s the difference between an agent and a trusted advisor.', deeper:'Ask "what would have to happen for this to be a great move for you?" and listen for the emotion under the logistics. The stated reason (more bedrooms) is rarely the real one (a baby coming, a parent moving in). Serve the real why and price, timing, and objections all get easier.' },
  { id:'past_clients', cat:'Your people', title:'The sale is the start, not the finish', body:'Most agents disappear after closing — which is exactly why most agents live on cold leads. Your past clients already know, like, and trust you; stay in their life and they become a referral engine that never runs dry. The relationship begins at the closing table.', deeper:'A repeat-and-referral business is the calmest, most profitable way to sell real estate — no chasing, just tending. Put every past client on a cadence, remember their home anniversary, be useful with no agenda. Five years of light, genuine touches turns one closing into a lifetime of business.' },
  { id:'give_first', cat:'Your people', title:'Give before you ask', body:'Reciprocity is the quietest force in relationships — offer something useful first (a market update, an introduction, a contractor you trust) and people naturally want to return the favor. Lead with generosity and you never have to chase.', deeper:'The value you give should cost them nothing and require nothing back — that\'s what makes it land. A neighbor\'s just-sold price, a great handyman, a "thought of you" note — small, genuine, no pitch attached. Do it consistently and when they or someone they know needs an agent, there\'s no competition.' },
  { id:'conversion', cat:'Your business', title:'Know your ratios, fix the weak link', body:'Your business is a funnel: conversations become appointments, appointments become clients, clients become closings. When you know your ratios, you stop guessing — you can see which step is leaking and fix that one thing instead of just working harder everywhere.', deeper:'If it takes 10 appointments to win 1 listing, your problem is your listing presentation, not your lead count — and more leads won\'t fix it. Track the whole funnel and the weakest number tells you where to invest. Improving one ratio a little multiplies through everything downstream.' },
  { id:'reviews', cat:'Your business', title:'Ask — for the review and the referral', body:'The two cheapest sources of business are a review and a referral, and most agents get neither because they never ask. A happy client at the closing table is at peak goodwill — that\'s the moment to ask, warmly and specifically. Reviews build the reputation that earns your next client before you ever meet them.', deeper:'Make the ask easy: send the direct link, suggest what to mention, ask right after a win. For referrals, be specific — "who do you know that\'s thinking about a move?" beats "send people my way." Systematize it so it happens every time, not just when you remember.' },
  { id:'know_market', cat:'Your business', title:'Know your market cold', body:'Authority comes from knowing your market better than anyone in the room — the inventory, the days on market, where prices are heading, what\'s selling and what\'s sitting. When you speak to the data with confidence, clients trust your advice on price and timing, and that trust closes deals.', deeper:'Pick your core neighborhoods and study them until you can quote them from memory. Preview listings, watch the solds, understand why one house moved in three days and another sat for three months. The agent who knows the market cold prices right, negotiates from strength, and never sounds like they\'re guessing.' },
  { id:'debrief', cat:'Your memory', title:'Debrief while it\'s hot', body:'The 60 seconds right after a showing or a listing appointment hold pure gold — what they loved, what worried them, what they let slip. Capture it immediately with a quick voice note, because by the time you\'re back at your desk half of it is already gone.', deeper:'Memory decays fastest in the first hour, and the details that fade first are exactly the ones that build relationships and close deals. A habit of debriefing in the car turns every appointment into lasting intelligence. Prism transcribes it and files it against the right person — you just talk for a minute.' },
  { id:'promises', cat:'Your memory', title:'Never drop a promise', body:'Trust in this business is built on doing the small things you said you\'d do — send the disclosure, call the lender, follow up Thursday. Drop one and the client remembers it far longer than the ten you kept. Capture every promise the moment you make it and it becomes a commitment you can\'t forget.', deeper:'The fastest way to lose a client isn\'t a bad negotiation — it\'s the quiet accumulation of small dropped balls. When you record your calls and capture your notes, every promise is on record and Prism can surface it as a task. Being the agent who always does what they said is a rarer edge than it should be.' },
  { id:'search', cat:'Your memory', title:'Capture once, find it forever', body:'The payoff of recording and noting everything is that nothing is ever truly lost — any conversation, promise, or detail is a quick search away. You stop relying on memory and start relying on a system that never forgets, which frees your mind to be present.', deeper:'"I think we discussed…" becomes "here\'s exactly what you said on the 12th." That precision feels like magic to clients and takes the anxiety of forgetting out of your day. The more you capture, the more valuable the search becomes — it compounds into a second brain for your whole business.' },
  { id:'compounding_intel', cat:'Your memory', title:'Your data compounds', body:'Every recording, note, and interaction makes Prism\'s read on each person sharper — their style, their motivation, their history with you. Unlike a memory that fades, this intelligence grows: the more you feed it, the better it prepares you for the next conversation. Small inputs, compounding returns.', deeper:'Most tools forget the moment you close them; a system that remembers gets more valuable every day you use it. A year of captured conversations is an asset no competitor can copy — it\'s your relationships, encoded. Feed it consistently and it becomes the quiet advantage that makes everything else easier.' },
  { id:'represent', cat:'Your craft', title:'Represent, don\'t sell', body:'You\'re not a salesperson pushing a product — you\'re a fiduciary hired to protect someone\'s biggest financial decision. Lead with their interest, even when it costs you a faster commission, and you earn the kind of trust that sends clients for life. The best agents advise; they never push.', deeper:'The moment a client senses you care more about the close than about them, you\'ve lost the relationship even if you win the deal. Tell them when a house is wrong, when the price is too high, when waiting is smarter. That integrity is slower in the moment and unbeatable over a career — it\'s the whole reason referrals exist.' },
  { id:'anchor', cat:'Your craft', title:'Anchor, then justify', body:'Every negotiation moves around the first number on the table, so the number you put down — and how you back it up — shapes everything after. Come in anchored to real evidence (comps, condition, market data), not a gut guess. Whoever frames the value with facts controls the conversation.', deeper:'An anchor without justification is just a demand, and it invites a fight; an anchor built on data invites agreement. Lay out the three solds that support your price before you state it, so the number feels inevitable rather than aggressive. And know your walk-away before you start — the negotiator who can leave is the one who sets the terms.' },
  { id:'objections', cat:'Your craft', title:'Agree first, then handle it', body:'When a client raises an objection, the instinct is to argue — and arguing makes them dig in. Instead acknowledge it first ("that\'s a fair concern"), then address it. People can\'t hear your answer until they feel heard, and a felt objection is usually just a request for reassurance.', deeper:'Most objections aren\'t the real issue — "the price is too high" often means "I\'m scared of overpaying" or "convince me this is right." Ask a question before you answer: "help me understand what\'s behind that?" You\'ll often find the objection dissolves once they talk it through, or reveals the real concern you can actually solve.' },
  { id:'price_right', cat:'Your craft', title:'Price it right the first time', body:'Overpricing is the silent deal-killer — a listing priced too high sits, goes stale, draws lowball offers, and sells for less than if it had been priced right on day one. The market doesn\'t care what a seller wishes; your job is to tell them the truth kindly and back it with data.', deeper:'The most showings and the strongest offers come in the first two weeks, while the listing is fresh — waste that window on an aspirational price and you never get it back. It\'s tempting to "buy the listing" by agreeing to a high number, but you\'re just signing up to renegotiate it downward later from a weaker position. Price to sell and you serve the seller; price to flatter and you cost them money.' },
  { id:'to_the_finish', cat:'Your craft', title:'Manage the deal to the finish line', body:'The contract isn\'t the finish — it\'s the start of the most fragile stretch, where inspections, appraisals, financing, and nerves quietly kill deals. Stay on top of every date and every party, communicate proactively, and solve problems before they become emergencies. Deals don\'t close themselves.', deeper:'A calendar of every contingency date, a check-in rhythm with the lender and title, and a client kept calm through the scary moments — that\'s the unglamorous work that separates a closed deal from a fallen-through one. Silence is where anxiety and lawsuits grow; over-communication is the cure. The agent who shepherds the transaction to the table gets the referral, not just the commission.' },
  { id:'pay_yourself', cat:'Your money', title:'Pay yourself a salary', body:'Commission income is lumpy — feast one month, famine the next — and that rollercoaster is what wrecks agents financially and emotionally. Route your commissions into a business account and pay yourself a steady monthly "salary," so your life runs on a predictable number instead of the timing of closings.', deeper:'When every check feels like it has to cover everything, you make desperate decisions and ride an emotional wave that hurts your work. Smoothing your income is how you think like a business owner instead of a lottery player. Decide what you need to live on, pay yourself that, and let the account absorb the swings.' },
  { id:'tax_aside', cat:'Your money', title:'Set aside taxes on every check', body:'No one withholds taxes from a commission check — that\'s your job, and the agents who skip it get a brutal surprise every spring. The moment a commission lands, move a set percentage (often 25–30%) into a separate account you don\'t touch. Pay it quarterly and tax season becomes a non-event.', deeper:'Owing money you already spent is one of the most stressful and avoidable holes in this business. Treat the tax portion as never having been yours — because it wasn\'t. PrismOS nudges you on quarterly estimates, but the habit is simple: every check, skim the tax off the top first, before it ever feels like income.' },
  { id:'dry_season', cat:'Your money', title:'Fund the dry season', body:'Real estate has slow stretches — winter, a soft market, a run of deals that fall through — and the agents who survive them saved during the good months. Build a cash reserve that covers several months of expenses so a slow season is an inconvenience, not a crisis.', deeper:'Fear is a terrible negotiating partner; a client can smell an agent who needs the deal, and desperation costs you both money and standards. A reserve buys you the freedom to walk away, to say no to bad-fit clients, to keep prospecting while others panic. The cushion isn\'t just financial security — it\'s what lets you operate from strength.' },
  { id:'rejection', cat:'Your mindset', title:'Rejection is the job, not a verdict', body:'This business runs on hearing no — no is the toll you pay on the road to yes, not a judgment of your worth. The agents who last stop taking it personally and start treating each no as one step closer to the next yes. Volume beats fragility.', deeper:'A no today is often a not-yet — the person who won\'t list this month may call you in six because you stayed gracious. Detach your identity from any single outcome and the whole game gets lighter and, ironically, more successful. Track your ratios: when you know it takes X conversations to get a yes, every no is just math, not misery.' },
  { id:'consistency', cat:'Your mindset', title:'Consistency beats intensity', body:'A burst of effort for two weeks followed by a month of nothing loses to steady, boring reps every day. Prospecting an hour a day, every day, compounds into a pipeline that never runs dry. This business rewards the tortoise, not the sprinter who burns out.', deeper:'The agents who blow up their numbers aren\'t doing heroic things — they\'re doing ordinary things without missing days. Motivation is unreliable; a habit you keep regardless of mood is what carries you through the flat stretches. Show up on the days you don\'t feel like it and you\'ll never need a comeback, because you never fell off.' },
  { id:'motion', cat:'Your mindset', title:'Motion creates motivation', body:'You don\'t wait to feel motivated and then act — you act, and the motivation follows. Make the first call while you\'re still reluctant and momentum takes over within minutes. Waiting to feel ready is how whole days disappear.', deeper:'Motivation is a result of action, not a prerequisite for it — this is the most freeing thing to understand about hard days. Lower the bar to start: "just one call," "just open the CRM." Starting is the whole battle; once you\'re moving, continuing is easy, and the confidence you were waiting for shows up on its own.' },
  { id:'marathon', cat:'Your mindset', title:'Protect your energy — it\'s a marathon', body:'A real-estate career is decades long, and burnout ends more careers than bad markets do. Guard your sleep, your health, your relationships, and your time off with the same discipline you give prospecting — a depleted agent serves no one well. The goal isn\'t a heroic year; it\'s a durable career.', deeper:'Hustle culture sells the all-nighter, but the agents still standing at the top after twenty years paced themselves. Boundaries — a hard stop, a real day off, a phone that goes silent — aren\'t laziness; they\'re what make the long game possible. Take care of the person doing the work and the work takes care of itself.' },
  { id:'list_to_last', cat:'Your business', title:'List to last', body:'Buyers take one at a time and eat your calendar; a listing markets itself, attracts more buyers and sellers, and works for you around the clock. Building a listing-based business is how you scale past the ceiling of your own hours. Chase listings and the rest follows.', deeper:'One sign in a yard generates calls, an open house fills your pipeline, and a sold sign advertises your results to the whole neighborhood — leverage a single buyer can never match. Buyers are a fine way to start, but a career built only on them caps out fast, because you can only be in one car at a time. Shift your prospecting toward listings and your business stops trading purely on your time.' },
  { id:'farm', cat:'Your business', title:'Own a neighborhood', body:'Pick an area and become its agent — the one whose name is on every other sign, whose market updates land in every mailbox, who everyone thinks of first. Geographic farming compounds: familiarity breeds trust, trust breeds listings, and listings breed more listings. Depth in one area beats a thin presence everywhere.', deeper:'Farming is a long game measured in quarters, not weeks — it takes consistent, valuable contact before the referrals start, which is exactly why most agents quit too early and it stays wide open. Know the data for your farm cold, show up in person, be genuinely useful, and let repetition work. In time you stop chasing that neighborhood\'s business and it starts coming to you.' },
  { id:'weekly_review', cat:'Your business', title:'Review your business weekly', body:'Spend 30 minutes each week looking at your own numbers — conversations had, appointments set, pipeline moved, goals on pace. What gets measured gets managed; agents who never check their scoreboard drift, while those who review course-correct before a slow week becomes a slow quarter.', deeper:'The weekly review is where you catch the leak early — the prospecting that slipped, the follow-ups that stalled, the goal quietly falling behind. It turns a vague "am I doing okay?" into a clear plan for the coming week. Treat it like an appointment with the CEO of your business, because that\'s exactly who you\'re meeting with.' },
  { id:'leverage', cat:'Your business', title:'Buy back your time', body:'Every hour you spend on $15 tasks is an hour stolen from the $500 work only you can do. As you grow, delegate the admin, the coordination, the errands — through tools, systems, or people — so your hours flow to prospecting, listing, and negotiating. You can\'t scale by doing everything yourself.', deeper:'List your tasks and mark which ones actually require you; most don\'t. The fear is that delegating costs money, but the real cost is the income you forfeit doing low-value work with high-value hours. Automate what you can, hand off what you can\'t automate, and protect your calendar for the few activities that truly move your business.' },
  { id:'segment', cat:'Your people', title:'Not every contact is equal', body:'A database works when you treat your raving fans differently from your cold acquaintances. Segment your people — your A\'s who send referrals, your B\'s who might, your C\'s you\'re nurturing — and spend the most energy where the most business lives. Broad and shallow loses to focused and deep.', deeper:'Your top relationships deserve more touches, more personalization, more of you — that\'s where repeat and referral business is born. Sort your database honestly and build a cadence per tier so nobody important slips and nobody unimportant eats your day. PrismOS\'s DISC reads and cadences make this practical: right message, right person, right rhythm.' },
  { id:'expectations', cat:'Your people', title:'Set expectations early', body:'Most client frustration comes from surprise, not from bad news — so tell them up front how the process works, what could go wrong, and how you\'ll communicate. An expectation set in advance is guidance; the same information delivered late feels like an excuse. Frame the road before you drive it.', deeper:'Walk a new client through the whole journey at the start — timelines, likely bumps, decisions they\'ll face, how and when you\'ll be in touch. When the inevitable hiccup comes, you\'ve already prepared them, and calm confidence replaces panic. The agent who sets expectations looks like a pro; the one who explains after the fact looks like they lost control.' },
  { id:'over_communicate', cat:'Your people', title:'Over-communicate during the deal', body:'The number one complaint about agents isn\'t competence — it\'s silence. During a transaction a client\'s anxiety fills any gap you leave, so update them even when there\'s nothing new ("no news yet, here\'s where we are"). A quick, proactive touch beats a perfect answer that comes too late.', deeper:'"No update" is itself an update to a nervous buyer or seller — silence reads as "something\'s wrong" or "they forgot about me." Set a rhythm (a check-in every few days, more near deadlines) and beat them to the question every time. You will almost never lose a client for talking to them too much.' },
  { id:'eat_frog', cat:'Your day', title:'Eat the frog', body:'Do the hardest, most-avoided thing first — the call you\'re dreading, the difficult conversation, the task that\'s been following you around. Knock it out before the day\'s noise starts and everything after feels easy. Procrastinated dread costs more energy sitting there than the task ever would.', deeper:'The thing you\'re avoiding is usually the thing that matters most — that\'s why your mind keeps flagging it. Done first, it can\'t hang over the whole day draining you, and the win gives you momentum for everything else. If it has to happen today, it happens first, before you can talk yourself out of it.' },
  { id:'plan_week', cat:'Your day', title:'Plan the week, not just the day', body:'A daily plan keeps you busy; a weekly plan keeps you strategic. Before the week starts, block your prospecting, your appointments, and your priorities across all seven days, so you\'re steering the week instead of reacting to it. Zoom out and the whole thing gets more intentional.', deeper:'When you plan only day to day, urgent things crowd out the important work that has no deadline — and a week slips by with your money hours never protected. A weekly view lets you place the big rocks first and fit the rest around them. Sunday evening or Monday morning, take fifteen minutes to design the week before it designs you.' },
];

export const MILESTONES = [
  { id:'first',  icon:'✦', label:'First light',   desc:'Learned your first lesson',           need:(s,L)=> s.filter(id=>L.some(l=>l.id===id)).length >= 1 },
  { id:'day',    icon:'☀️', label:'Day master',    desc:'Learned everything in Your day',      need:(s,L)=> L.filter(l=>l.cat==='Your day').every(l=>s.includes(l.id)) },
  { id:'people', icon:'👥', label:'People reader',  desc:'Learned everything in Your people',   need:(s,L)=> L.filter(l=>l.cat==='Your people').every(l=>s.includes(l.id)) },
  { id:'biz',    icon:'📈', label:'Numbers person', desc:'Learned everything in Your business', need:(s,L)=> L.filter(l=>l.cat==='Your business').every(l=>s.includes(l.id)) },
  { id:'memory', icon:'🧠', label:'Total recall',   desc:'Learned everything in Your memory',   need:(s,L)=> L.filter(l=>l.cat==='Your memory').every(l=>s.includes(l.id)) },
  { id:'craft',   icon:'🤝', label:'Deal-maker',   desc:'Learned everything in Your craft',   need:(s,L)=> L.filter(l=>l.cat==='Your craft').every(l=>s.includes(l.id)) },
  { id:'money',   icon:'💰', label:'Money-wise',   desc:'Learned everything in Your money',   need:(s,L)=> L.filter(l=>l.cat==='Your money').every(l=>s.includes(l.id)) },
  { id:'mindset', icon:'🧭', label:'Steady mind',  desc:'Learned everything in Your mindset', need:(s,L)=> L.filter(l=>l.cat==='Your mindset').every(l=>s.includes(l.id)) },
  { id:'usingprism', icon:'🔷', label:'Prism fluent', desc:'Learned every Using Prism guide', need:(s,L)=> L.filter(l=>l.cat==='Using Prism').every(l=>s.includes(l.id)) },
  { id:'pro',    icon:'🏆', label:'PrismOS Pro',    desc:'Learned every fundamental',           need:(s,L)=> L.every(l=>s.includes(l.id)) },
];

export const TRIGGER_META = {
  cold_contacts: { label:'People going cold', hint:'Fires when at least [threshold] contacts have had no touch in [days]+ days.', hasDays:true },
  no_cadence:    { label:'Contacts without a cadence', hint:'Fires when you have [threshold]+ contacts and fewer than ~10% have a cadence set.', hasDays:false },
  review_backlog:{ label:'Review backlog', hint:'Fires when [threshold]+ items are waiting in Review.', hasDays:false },
  owe_replies:   { label:'Owed replies', hint:'Fires when you owe [threshold]+ people a reply.', hasDays:false },
  overdue_tasks: { label:'Overdue tasks', hint:'Fires when [threshold]+ tasks are past due.', hasDays:false },
};

export const CAT_OPTIONS = ['Your day','Your people','Your business','Your memory','Your craft','Your money','Your mindset'];

export const VIEW_OPTIONS = [ ['contacts','Contacts'], ['review','Review'], ['tasks','Tasks'], ['prospecting','Prospecting'], ['finance','Finance'], ['calendar','Calendar'], ['dashboard','Dashboard'] ];

export function TeachingStudio({ userId, onClose }){
  const [tab, setTab] = useState('lessons');
  const [lessons, setLessons] = useState([]);
  const [triggers, setTriggers] = useState([]);
  const [msg, setMsg] = useState('');
  const [lf, setLf] = useState({ category:'Your business', title:'', body:'', deeper:'' });
  const [tf, setTf] = useState({ template:'cold_contacts', threshold:8, days:75, title:'', why:'', cta_label:'Open', cta_view:'contacts', priority:5 });
  const load = React.useCallback(async () => {
    try { const [{ data: L }, { data: T }] = await Promise.all([ supabase.from('teaching_lessons').select('*').order('created_at', { ascending:false }), supabase.from('teaching_triggers').select('*').order('created_at', { ascending:false }) ]); setLessons(L||[]); setTriggers(T||[]); } catch (_) {}
  }, []);
  React.useEffect(() => { load(); }, [load]);
  const addLesson = async () => {
    if (!lf.title.trim() || !lf.body.trim()) { setMsg('Title and body are required.'); return; }
    try { await supabase.from('teaching_lessons').insert({ category: lf.category, title: lf.title.trim(), body: lf.body.trim(), deeper: lf.deeper.trim() || null, created_by: userId }); setLf({ category:'Your business', title:'', body:'', deeper:'' }); setMsg('Lesson added — it’s live in Learn.'); load(); } catch (_) { setMsg('Could not save.'); }
  };
  const delLesson = async (id) => { if (!window.confirm('Delete this lesson?')) return; try { await supabase.from('teaching_lessons').delete().eq('id', id); load(); } catch (_) {} };
  const toggleLesson = async (l) => { try { await supabase.from('teaching_lessons').update({ active: !l.active }).eq('id', l.id); load(); } catch (_) {} };
  const addTrigger = async () => {
    if (!tf.title.trim() || !tf.why.trim()) { setMsg('Title and why are required.'); return; }
    try { await supabase.from('teaching_triggers').insert({ template: tf.template, threshold: parseInt(tf.threshold) || 1, days: tf.template === 'cold_contacts' ? (parseInt(tf.days) || 75) : null, title: tf.title.trim(), why: tf.why.trim(), cta_label: tf.cta_label.trim() || 'Open', cta_view: tf.cta_view, priority: parseInt(tf.priority) || 5, created_by: userId }); setTf({ template:'cold_contacts', threshold:8, days:75, title:'', why:'', cta_label:'Open', cta_view:'contacts', priority:5 }); setMsg('Trigger added — it’ll surface when the gap appears.'); load(); } catch (_) { setMsg('Could not save.'); }
  };
  const delTrigger = async (id) => { if (!window.confirm('Delete this trigger?')) return; try { await supabase.from('teaching_triggers').delete().eq('id', id); load(); } catch (_) {} };
  const toggleTrigger = async (t) => { try { await supabase.from('teaching_triggers').update({ active: !t.active }).eq('id', t.id); load(); } catch (_) {} };
  const lbl = { fontSize:11, fontWeight:700, color:'#C8BFAE', margin:'10px 0 4px' };
  const tabBtn = (id, label) => <button onClick={() => { setTab(id); setMsg(''); }} className="btn btn-ghost btn-sm" style={{ borderColor: tab===id?'#CBA35C':'rgba(203,163,92,.3)', color: tab===id?'#EBCB82':'#C8BFAE' }}>{label}</button>;
  return (
    <div className="ww-prism">
      <style>{`.ww-prism{--text-1:#F6F1E7;--text-2:#C8BFAE;--text-3:#8C8475;font-family:Manrope,sans-serif;background:#100D09;min-height:100%;} .ww-prism .form-input{background:#0c0a07;border:1px solid rgba(203,163,92,.24);color:#F6F1E7;border-radius:8px;padding:9px 11px;font-size:13px;font-family:inherit;box-sizing:border-box;width:100%;} .ww-prism .btn-primary{background:#EBCB82;color:#1a1409;border:none;} .ww-prism .btn-ghost{border:1px solid rgba(203,163,92,.3);color:#C8BFAE;background:transparent;} .ww-prism .panel{background:linear-gradient(180deg,#18130D,#100D09);border:1px solid rgba(203,163,92,.2);border-radius:14px;padding:14px;}`}</style>
      <button onClick={onClose} className="btn btn-ghost btn-sm" style={{ marginBottom:12 }}>← Back to Learn</button>
      <h2 style={{ fontFamily:'Fraunces, serif', fontWeight:300, fontSize:28, margin:'0 0 4px', color:'#F6F1E7' }}>Teaching Studio</h2>
      <p style={{ fontSize:12.5, color:'#8C8475', margin:'0 0 14px' }}>Write lessons and coaching triggers for every agent — they go live instantly, no update needed.</p>
      <div style={{ display:'flex', gap:8, marginBottom:16 }}>{tabBtn('lessons','Lessons')}{tabBtn('triggers','Coaching triggers')}</div>
      {msg && <div style={{ fontSize:12, color:'#EBCB82', marginBottom:12 }}>{msg}</div>}

      {tab === 'lessons' && (<>
        <div className="panel" style={{ marginBottom:16 }}>
          <div style={{ fontSize:13, fontWeight:700, color:'#F6F1E7', marginBottom:4 }}>New lesson</div>
          <div style={lbl}>Category</div>
          <select className="form-input" value={lf.category} onChange={e => setLf({ ...lf, category:e.target.value })}>{CAT_OPTIONS.map(c => <option key={c} value={c}>{c}</option>)}</select>
          <div style={lbl}>Title</div>
          <input className="form-input" value={lf.title} onChange={e => setLf({ ...lf, title:e.target.value })} placeholder="e.g. Ask for the referral" />
          <div style={lbl}>The why (short)</div>
          <textarea className="form-input" rows={3} value={lf.body} onChange={e => setLf({ ...lf, body:e.target.value })} placeholder="Two or three sentences on why this matters." />
          <div style={lbl}>Go deeper (optional)</div>
          <textarea className="form-input" rows={3} value={lf.deeper} onChange={e => setLf({ ...lf, deeper:e.target.value })} placeholder="A fuller explanation for those who want it." />
          <button onClick={addLesson} className="btn btn-primary btn-sm" style={{ marginTop:12 }}>Add lesson</button>
        </div>
        <div style={{ fontSize:11, fontWeight:700, letterSpacing:'.2em', textTransform:'uppercase', color:'#CBA35C', marginBottom:8 }}>Your lessons ({lessons.length})</div>
        {lessons.length === 0 && <div style={{ fontSize:12.5, color:'#8C8475' }}>No custom lessons yet.</div>}
        {lessons.map(l => (
          <div key={l.id} className="panel" style={{ marginBottom:8, opacity: l.active?1:0.5 }}>
            <div style={{ display:'flex', alignItems:'center', gap:8 }}>
              <div style={{ flex:1, minWidth:0 }}>
                <div style={{ fontSize:13, fontWeight:700, color:'#F6F1E7' }}>{l.title}</div>
                <div style={{ fontSize:11, color:'#8C8475' }}>{l.category}{l.active?'':' · hidden'}</div>
              </div>
              <button onClick={() => toggleLesson(l)} className="btn btn-ghost btn-sm" style={{ fontSize:11 }}>{l.active?'Hide':'Show'}</button>
              <button onClick={() => delLesson(l.id)} className="btn btn-ghost btn-sm" style={{ fontSize:11 }}>Delete</button>
            </div>
          </div>
        ))}
      </>)}

      {tab === 'triggers' && (<>
        <div className="panel" style={{ marginBottom:16 }}>
          <div style={{ fontSize:13, fontWeight:700, color:'#F6F1E7', marginBottom:4 }}>New coaching trigger</div>
          <div style={lbl}>When this happens</div>
          <select className="form-input" value={tf.template} onChange={e => setTf({ ...tf, template:e.target.value })}>{Object.keys(TRIGGER_META).map(k => <option key={k} value={k}>{TRIGGER_META[k].label}</option>)}</select>
          <div style={{ fontSize:11, color:'#8C8475', marginTop:5 }}>{TRIGGER_META[tf.template].hint}</div>
          <div style={{ display:'flex', gap:10 }}>
            <div style={{ flex:1 }}><div style={lbl}>Threshold</div><input className="form-input" type="number" value={tf.threshold} onChange={e => setTf({ ...tf, threshold:e.target.value })} /></div>
            {TRIGGER_META[tf.template].hasDays && <div style={{ flex:1 }}><div style={lbl}>Days</div><input className="form-input" type="number" value={tf.days} onChange={e => setTf({ ...tf, days:e.target.value })} /></div>}
            <div style={{ width:90 }}><div style={lbl}>Priority</div><input className="form-input" type="number" value={tf.priority} onChange={e => setTf({ ...tf, priority:e.target.value })} /></div>
          </div>
          <div style={lbl}>Headline</div>
          <input className="form-input" value={tf.title} onChange={e => setTf({ ...tf, title:e.target.value })} placeholder="e.g. Time to work your database" />
          <div style={lbl}>The why</div>
          <textarea className="form-input" rows={3} value={tf.why} onChange={e => setTf({ ...tf, why:e.target.value })} placeholder="Why this matters, in your voice." />
          <div style={{ display:'flex', gap:10 }}>
            <div style={{ flex:1 }}><div style={lbl}>Button label</div><input className="form-input" value={tf.cta_label} onChange={e => setTf({ ...tf, cta_label:e.target.value })} /></div>
            <div style={{ flex:1 }}><div style={lbl}>Button opens</div><select className="form-input" value={tf.cta_view} onChange={e => setTf({ ...tf, cta_view:e.target.value })}>{VIEW_OPTIONS.map(([v,n]) => <option key={v} value={v}>{n}</option>)}</select></div>
          </div>
          <button onClick={addTrigger} className="btn btn-primary btn-sm" style={{ marginTop:12 }}>Add trigger</button>
        </div>
        <div style={{ fontSize:11, fontWeight:700, letterSpacing:'.2em', textTransform:'uppercase', color:'#CBA35C', marginBottom:8 }}>Your triggers ({triggers.length})</div>
        {triggers.length === 0 && <div style={{ fontSize:12.5, color:'#8C8475' }}>No custom triggers yet.</div>}
        {triggers.map(t => (
          <div key={t.id} className="panel" style={{ marginBottom:8, opacity: t.active?1:0.5 }}>
            <div style={{ display:'flex', alignItems:'center', gap:8 }}>
              <div style={{ flex:1, minWidth:0 }}>
                <div style={{ fontSize:13, fontWeight:700, color:'#F6F1E7' }}>{t.title}</div>
                <div style={{ fontSize:11, color:'#8C8475' }}>{(TRIGGER_META[t.template]||{}).label || t.template} · ≥{t.threshold}{t.days?(' · '+t.days+'d'):''}{t.active?'':' · off'}</div>
              </div>
              <button onClick={() => toggleTrigger(t)} className="btn btn-ghost btn-sm" style={{ fontSize:11 }}>{t.active?'Off':'On'}</button>
              <button onClick={() => delTrigger(t.id)} className="btn btn-ghost btn-sm" style={{ fontSize:11 }}>Delete</button>
            </div>
          </div>
        ))}
      </>)}
    </div>
  );
}

export function LearnView({ setView, userId, isAdmin = false }){
  const [seen, setSeen] = useState(() => tipsSeenList());
  const [open, setOpen] = useState(null);
  const [deepId, setDeepId] = useState(null);
  const [custom, setCustom] = useState([]);
  const [studioOpen, setStudioOpen] = useState(false);
  const loadCustom = React.useCallback(async () => {
    try { const { data } = await supabase.from('teaching_lessons').select('*').eq('active', true).order('sort', { ascending: true }); setCustom((data || []).map(r => ({ id:'tl_'+r.id, cat: r.category || 'Your business', title: r.title, body: r.body, deeper: r.deeper || '' }))); } catch (_) {}
  }, []);
  React.useEffect(() => { loadCustom(); }, [loadCustom]);
  const allLessons = [...LESSONS, ...custom];
  const total = allLessons.length;
  const learned = allLessons.filter(l => seen.includes(l.id)).length;
  const cats = [];
  allLessons.forEach(l => { if (!cats.includes(l.cat)) cats.push(l.cat); });
  const earnedCount = MILESTONES.filter(m => m.need(seen, allLessons)).length;
  const toggle = (id) => {
    setOpen(o => o === id ? null : id); setDeepId(null);
    if (!seen.includes(id)) { try { const arr = tipsSeenList(); arr.push(id); localStorage.setItem('prism_tips_seen', JSON.stringify(arr)); } catch(_){} setSeen(tipsSeenList()); }
  };
  if (studioOpen) return <TeachingStudio userId={userId} onClose={() => { setStudioOpen(false); loadCustom(); }} />;
  return (
    <div className="ww-prism">
      <style>{`.ww-prism{--bg-base:#100D09;--bg-card:#1B1610;--border:rgba(203,163,92,.20);--accent:#CBA35C;--text-1:#F6F1E7;--text-2:#C8BFAE;--text-3:#8C8475;font-family:Manrope,sans-serif;background:radial-gradient(120% 26% at 50% -4%, rgba(203,163,92,.10), transparent 60%), #100D09;min-height:100%;} .ww-prism .ww-eyebrow{font-size:10.5px;font-weight:700;letter-spacing:.24em;text-transform:uppercase;color:#CBA35C;} .ww-prism .form-input{background:#0c0a07;border:1px solid rgba(203,163,92,.24);color:#F6F1E7;border-radius:8px;padding:9px 11px;font-size:13px;font-family:inherit;box-sizing:border-box;width:100%;} .ww-prism .btn-primary{background:#EBCB82;color:#1a1409;border:none;} .ww-prism .btn-ghost{border:1px solid rgba(203,163,92,.3);color:#C8BFAE;background:transparent;}`}</style>
      <div style={{ display:'flex', alignItems:'flex-start', justifyContent:'space-between', gap:10 }}>
        <div>
          <div style={{ fontSize:10.5, fontWeight:700, letterSpacing:'.24em', textTransform:'uppercase', color:'#CBA35C', marginBottom:6 }}>The Field Guide</div>
          <h2 style={{ fontFamily:'Fraunces, serif', fontWeight:300, fontSize:30, letterSpacing:'-.02em', margin:'0 0 4px', color:'#F6F1E7' }}>The Prism Field Guide</h2>
        </div>
        {isAdmin && <button onClick={() => setStudioOpen(true)} className="btn btn-ghost btn-sm" style={{ flexShrink:0, marginTop:6, fontSize:11 }}>✎ Studio</button>}
      </div>
      <p style={{ fontSize:13, color:'#C8BFAE', margin:'0 0 16px' }}>Your guide to Prism and the craft — short lessons on how to use every feature and the why behind the work. Read them here anytime, or let them surface as you go.</p>
      <div style={{ background:'linear-gradient(180deg,#1B1610,#100D09)', border:'1px solid rgba(203,163,92,.28)', borderRadius:16, padding:'14px 16px', marginBottom:18 }}>
        <div style={{ display:'flex', alignItems:'baseline', gap:8, marginBottom:8 }}>
          <span style={{ fontFamily:'Fraunces, serif', fontSize:26, fontWeight:300, color:'#EBCB82', lineHeight:1 }}>{learned}</span>
          <span style={{ fontSize:12.5, color:'#C8BFAE' }}>of {total} fundamentals learned</span>
        </div>
        <div style={{ height:6, borderRadius:100, background:'rgba(203,163,92,.15)', overflow:'hidden' }}><div style={{ height:'100%', width:(total? Math.round(learned/total*100):0)+'%', background:'linear-gradient(90deg,#CBA35C,#EBCB82)', borderRadius:100, transition:'width .4s' }} /></div>
      </div>
      <div style={{ marginBottom:22 }}>
        <div style={{ fontSize:10.5, fontWeight:700, letterSpacing:'.22em', textTransform:'uppercase', color:'#CBA35C', marginBottom:8 }}>Milestones · {earnedCount}/{MILESTONES.length}</div>
        <div style={{ display:'flex', gap:8, overflowX:'auto', paddingBottom:4 }}>
          {MILESTONES.map(m => { const got = m.need(seen, allLessons); return (
            <div key={m.id} title={m.desc} style={{ flexShrink:0, width:96, textAlign:'center', padding:'12px 8px', borderRadius:12, border:'1px solid '+(got?'#CBA35C':'rgba(203,163,92,.16)'), background: got?'rgba(203,163,92,.1)':'transparent' }}>
              <div style={{ fontSize:22, marginBottom:4, filter: got?'none':'grayscale(1)', opacity: got?1:0.4 }}>{m.icon}</div>
              <div style={{ fontSize:10.5, fontWeight:700, color: got?'#EBCB82':'#8C8475', lineHeight:1.2 }}>{m.label}</div>
            </div>
          ); })}
        </div>
      </div>
      {cats.map(cat => (
        <div key={cat} style={{ marginBottom:20 }}>
          <div style={{ fontSize:10.5, fontWeight:700, letterSpacing:'.22em', textTransform:'uppercase', color:'#CBA35C', marginBottom:8 }}>{cat}</div>
          {allLessons.filter(l => l.cat === cat).map(l => {
            const isSeen = seen.includes(l.id); const isOpen = open === l.id;
            return (
              <div key={l.id} style={{ border:'1px solid '+(isOpen?'rgba(203,163,92,.4)':'rgba(203,163,92,.16)'), borderRadius:12, marginBottom:8, background: isOpen?'rgba(203,163,92,.06)':'transparent', overflow:'hidden' }}>
                <button onClick={() => toggle(l.id)} style={{ display:'flex', alignItems:'center', gap:11, width:'100%', textAlign:'left', padding:'12px 14px', background:'transparent', border:'none', cursor:'pointer' }}>
                  <span style={{ width:18, height:18, flexShrink:0, borderRadius:'50%', display:'flex', alignItems:'center', justifyContent:'center', fontSize:11, fontWeight:800, border:'1.5px solid '+(isSeen?'#CBA35C':'#5a5348'), background:isSeen?'#CBA35C':'transparent', color:isSeen?'#1a1409':'transparent' }}>✓</span>
                  <span style={{ flex:1, fontSize:13.5, fontWeight:700, color:'#F6F1E7' }}>{l.title}</span>
                  <span style={{ fontSize:18, color:'#8C8475' }}>{isOpen ? '−' : '+'}</span>
                </button>
                {isOpen && (
                  <div style={{ padding:'0 14px 14px 43px' }}>
                    <div style={{ fontSize:13, lineHeight:1.6, color:'#C8BFAE' }}>{l.body}</div>
                    {l.deeper && (<>
                      <button onClick={() => setDeepId(d => d === l.id ? null : l.id)} style={{ marginTop:10, background:'transparent', border:'none', color:'#CBA35C', fontSize:12, fontWeight:700, cursor:'pointer', padding:0 }}>{deepId === l.id ? 'Show less' : 'Go deeper ↓'}</button>
                      {deepId === l.id && <div style={{ marginTop:8, fontSize:13, lineHeight:1.65, color:'#C8BFAE', paddingLeft:12, borderLeft:'2px solid rgba(203,163,92,.4)' }}>{l.deeper}</div>}
                    </>)}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      ))}
      <div style={{ fontSize:11.5, color:'#8C8475', marginTop:4 }}>Set how often lessons surface as you work in Settings → Learning pace.</div>
    </div>
  );
}
