import { chromium } from 'playwright';
const URL = process.env.SMOKE_URL, OUT='/home/claude/shots5';
const b = await chromium.launch({ headless:true, args:['--no-sandbox'] });
const c = await b.newContext({ viewport:{width:390,height:844}, deviceScaleFactor:2 });
const page = await c.newPage();
page.on('pageerror', e=>console.log('PAGEERROR:', e.message));
await page.goto(URL,{waitUntil:'domcontentloaded',timeout:30000});
await page.waitForSelector('input[type="email"]',{timeout:20000});
await page.fill('input[type="email"]', process.env.SMOKE_EMAIL);
await page.fill('input[type="password"]', process.env.SMOKE_PASSWORD);
await page.click('button:has-text("Sign In")');
await page.waitForFunction(()=>typeof window.__setView==='function',{timeout:35000});
await page.waitForTimeout(2500);
await page.addStyleTag({content:'.modal-overlay{display:none !important;}'});
await page.evaluate(()=>{Object.keys(localStorage).filter(k=>k.startsWith('prism.room.spot.')).forEach(k=>localStorage.removeItem(k));});
await page.evaluate(()=>window.__setView('today'));
await page.waitForTimeout(1000);
await page.click('[aria-label="Menu"]');
await page.waitForTimeout(900);
await page.screenshot({path:`${OUT}/sidebar.png`});
console.log('ORDER:', JSON.stringify(await page.evaluate(()=>[...document.querySelectorAll('.sidebar .nav-item')].slice(0,5).map(n=>n.innerText.trim()))));
await page.evaluate(()=>{const n=[...document.querySelectorAll('.sidebar .nav-item')].find(x=>x.innerText.trim().startsWith('My World')); if(n) n.click();});
await page.waitForTimeout(2000);
console.log('LANDED:', await page.evaluate(()=>window.__getView&&window.__getView()));
await page.evaluate(()=>window.__setView('calendar')); await page.waitForTimeout(1200);
await page.evaluate(()=>window.__setView('today')); await page.waitForTimeout(800);
await page.click('[aria-label="Menu"]'); await page.waitForTimeout(800);
await page.evaluate(()=>{const n=[...document.querySelectorAll('.sidebar .nav-item')].find(x=>x.innerText.trim().startsWith('My World')); if(n) n.click();});
await page.waitForTimeout(2000);
console.log('RESUMED:', await page.evaluate(()=>window.__getView&&window.__getView()));
await b.close();
